/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Volcano Hosting API
 * Public API for Volcano Hosting clients, SDKs, and CLI tooling (Port 8000).
 *
 * This specification intentionally excludes first-party/internal APIs. See api/openapi-internal.yaml for non-public internal and Builder operations.
 * OpenAPI spec version: 3.0.0
 */
export const CreateDatabaseRequestRegion = {
    'aws-us-east-1': 'aws-us-east-1',
    'aws-us-east-2': 'aws-us-east-2',
    'aws-us-west-2': 'aws-us-west-2',
    'aws-eu-central-1': 'aws-eu-central-1',
    'aws-eu-west-2': 'aws-eu-west-2',
    'aws-ap-southeast-1': 'aws-ap-southeast-1',
    'aws-ap-southeast-2': 'aws-ap-southeast-2',
    'aws-sa-east-1': 'aws-sa-east-1',
};
