/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Volcano Hosting API
 * Public API for Volcano Hosting clients, SDKs, and CLI tooling (Port 8000).
 *
 * This specification intentionally excludes first-party/internal APIs. See api/openapi-internal.yaml for non-public internal and Builder operations.
 * OpenAPI spec version: 3.0.0
 */
export const CreateFunctionBodyRuntime = {
    nodejs22x: 'nodejs22.x',
    nodejs24x: 'nodejs24.x',
    python310: 'python3.10',
    python311: 'python3.11',
    python312: 'python3.12',
    python313: 'python3.13',
    python314: 'python3.14',
    ruby33: 'ruby3.3',
    ruby34: 'ruby3.4',
    ruby40: 'ruby4.0',
};
