/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Volcano Hosting API
 * Public API for Volcano Hosting clients, SDKs, and CLI tooling (Port 8000).
 *
 * This specification intentionally excludes first-party/internal APIs. See api/openapi-internal.yaml for non-public internal and Builder operations.
 * OpenAPI spec version: 3.0.0
 */
export const HostedRenderablePageType = {
    signup: 'signup',
    'forgot-password': 'forgot-password',
    device: 'device',
    'verify-email': 'verify-email',
    'reset-password': 'reset-password',
};
