/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Volcano Hosting API
 * Public API for Volcano Hosting clients, SDKs, and CLI tooling (Port 8000).
 *
 * This specification intentionally excludes first-party/internal APIs. See api/openapi-internal.yaml for non-public internal and Builder operations.
 * OpenAPI spec version: 3.0.0
 */
export const ProjectMetricsQueryTimeRangeWindow = {
    '30m': '30m',
    '1h': '1h',
    '24h': '24h',
    '7d': '7d',
};
