name: Lint docs

on:
  pull_request:
    paths:
      - 'docs/**'

permissions:
  contents: read

jobs:
  docs:
    uses: Kong/volcano-docs/.github/workflows/lint-docs.yml@main
    with:
      path: docs
